### ISSUE TITLE
FP8 instead of BF16?

### ISSUE THREAD

**Issue by drphero** [lujiazho/ComfyUI-CatvtonFluxWrapper#1]
Thanks for making these nodes. Since a 24GB GPU isn't enough to run this, do you think it's possible to load and change the diffusers model to fp8_e4m3fn instead of bf16 like the Load Diffusion Model node can with UNets?

**Comment by lujiazho** [comment]
You can do it now.

**Comment by drphero** [comment]
Just to make sure I understand: In order to use fp8, it must be used like the other in-conext loras by combining images and thus degrading the output?

What I was talking about before was if it was possible to load the diffusers model as fp8, thus keeping the ability to generate higher quality images while still fitting within 24GB of VRAM.
