### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by eokoo** [lujiazho/ComfyUI-CatvtonFluxWrapper#2]
![image](https://github.com/user-attachments/assets/14fcdeca-03fd-44a5-90a9-356bd26ee842)
I logged into huggingface and created a token, but where exactly does the token fill out? Please tell me, thank you.

**Comment by raymondgp** [comment]
Workaround: if you first set you huggingface token in as environments it'll work.
Getting a token on your huggingface account: https://huggingface.co/docs/hub/en/security-tokens
Setting the environment variable BEFORE you start Comfy (in the same command prompt):
set HF_TOKEN=PUT-YOUR-TOKEN-HERE
set HUGGING_FACE_HUB_TOKEN=PUT-YOUR-TOKEN-HERE

**Comment by alenknight** [comment]
this worked.... thank you!  this honestly should be part of the install instructions as most folks run portable version and will run into this issue.

**Comment by lujiazho** [comment]
Thanks for @raymondgp 's solution and @alenknight 's suggestion! I tested this with token set up long time ago so I didn't notice this could lead to problem. I updated the instructions already.

**Comment by anakein** [comment]
comfyui into stability matrix i cant connect with hugging face.
i tried  @raymondgp 's solution  but dont work.
