### ISSUE TITLE
Promotion for Float8 Types is not supported, attempted to promote Float8_e4m3fn and BFloat16

### ISSUE THREAD

**Issue by drphero** [lujiazho/ComfyUI-CatvtonFluxWrapper#3]
When attempting to use the Catvton-LoRA-Draw.json workflow, the Load Catvton Flux LoRA node takes about 35 minutes on a 3090 and ends with this error:

```
Start combining the model ...
!!! Exception during processing !!! Promotion for Float8 Types is not supported, attempted to promote Float8_e4m3fn and BFloat16
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-CatvtonFluxWrapper/nodes.py", line 179, in load_catvton_flux_lora
    state_dict[key] += lora_sd[key].to(load_device)
RuntimeError: Promotion for Float8 Types is not supported, attempted to promote Float8_e4m3fn and BFloat16
```

**Comment by lujiazho** [comment]
Which fp8 flux fill do you use? I managed to run it with https://civitai.com/models/969431/flux-fill-fp8.

**Comment by umiyuki** [comment]
I am getting the exact same error at mine, using https://civitai.com/models/969431/flux-fill-fp8 , running on WSL2 with RTX4090.

**Comment by drphero** [comment]
After 15 minutes of waiting for the lora to be loaded with the fp8 model from civitai (has to happen every time after comfy starts), I gave up and decided to try LoraLoaderModelOnly. It seems that no conversion is needed?

With lora loaded via LoraLoaderModelOnly:
![ComfyUI_temp_txeni_00003_](https://github.com/user-attachments/assets/5e38acee-e164-41a8-8b77-7bf54e1de988)

With lora disabled:
![ComfyUI_temp_txeni_00002_](https://github.com/user-attachments/assets/bbf0fd87-dde2-425f-aecc-82c298e9beb9)

**Comment by lujiazho** [comment]
You are right @drphero ! I'm not very familiar with ComfyUI built-in nodes yet, and I find the model params keys are different from lora so I just converted them. But yeah these can be done with LoraLoaderModelOnly, which leads to exactly same results (I just checked) as my conversion node. I already updated the workflow. Thanks!

**Comment by umiyuki** [comment]
Thanks for the workflow fix, it works great and gives results comparable to the Spaces demo.
