### ISSUE TITLE
Lora Conversion hangs

### ISSUE THREAD

**Issue by alenknight** [lujiazho/ComfyUI-CatvtonFluxWrapper#5]
trying with FP8 version (and did the full version too) but i'm getting to the Flux Fill LORA node and it just hangs.
tried the original DRAW json as well, and it hangs on the sampler.  
i'm running with an rtx 3090.  VRAM and all resources seem ok... it just hangs.  looking at all system resources... nothing seems overloaded. 
I also tried the Q5 gguf model just out of curiosity if it was VRAM issue...

![Screenshot 2024-12-02 at 12 10 27 PM](https://github.com/user-attachments/assets/3fd24155-e185-4f69-9dc7-ac523700a2e2)

**Comment by lujiazho** [comment]
The workflow is updated with built-in nodes of comfyui, you should be fine with the new one.
