### ISSUE TITLE
(not an issue) LORA?

### ISSUE THREAD

**Issue by alenknight** [lujiazho/ComfyUI-CatvtonFluxWrapper#6]
noticed you got CATVTON_flux_lora.safetensors as a model to load... is that something we need?  custom model you have or is there one we should be downloading?

otherwise, it all works great now!  thanks.  love this node.

**Comment by lujiazho** [comment]
`CATVTON_flux_lora.safetensors` is just the same LoRA in https://huggingface.co/xiaozaa/catvton-flux-lora-alpha, I renamed it.

**Comment by alenknight** [comment]
got it.  thanks!
